import { getHomePage, getProjects } from '../lib/api';
import Project from '../components/Project';
import Head from 'next/head';
import React from 'react';

import styles from '../styles/Home.module.css';

export default function Home({ homePageData, projectsData }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
              {projectsData !== undefined &&
              projectsData.map((p, index) => {
                        return <Project key={index} projectData={p} />;
                    })}
            </div>
        </div>
    );
}

export async function getStaticProps() {
    const homePageData = await getHomePage();

    const projectsData = await getProjects();

    return {
        props: {
            homePageData,
            projectsData,
        },
    };
}
